AAA_CSR_Support_Tool/Controllers/DealerController.cs
using AAA_CSR_Support_Tool.BusinessLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAA_CSR_Support_Tool.Controllers
{
    public class DealerController : Controller
    {
        private readonly IDataAccess _dataAccess;

        public DealerController(IDataAccess da)
        {
            _dataAccess = da;
        }
        // GET: Dealers
        public ActionResult Index()
        {
            var data = _dataAccess.GetAllDealersFromAAAA();

            return View(data);
        }

        [HttpPost]
        public ActionResult ChangeName(int dealerId, string new_name)
        {
            System.Int32 row;
            row = _dataAccess.ChangeDealerName(dealerId, new_name);
            if(row > 0)
                return Json(new { result = true });
            else
                return Json(new { result = false });
        }

        [HttpPost]
        public ActionResult Undo(int dealerId)
        {
            System.Int32 row;
            row = _dataAccess.UndoChangedName(dealerId);
            if (row > 0)
                return Json(new { result = true });
            else
                return Json(new { result = false });
        }
        
    }
}

AAA_CSR_Support_Tool/Controllers/HomenetController.cs
using AAA_CSR_Support_Tool.BusinessLayer;
using AAA_CSR_Support_Tool.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AAA_CSR_Support_Tool.Controllers
{
    public class HomenetController : Controller
    {

        private readonly IDataAccess _dataAccess;

        public HomenetController(IDataAccess da)
        {
            _dataAccess = da;
        }

        // GET: Homenet
        public ActionResult Index()
        {
            var homenetDealers = _dataAccess.GetAllHomenetDealers();

            return View(homenetDealers);
        }

        public ActionResult AddDealer()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddDealer(DealerCodeModel model)
        {
            string status;
            status = _dataAccess.AddHomenetDealerCode(model.DealerCode);

            if(status == "Added")
            {
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.ErrMsg = status;
                return View(model);
            }
                
        }

        public ActionResult ToggleActiveStatus(int accountId, int status)
        {
            var affecteRow = _dataAccess.ChangeHomenetDealerStatus(accountId, status);
            bool success = false;
            string opsStatus = string.Empty;
            if (affecteRow > 0)
            {
                opsStatus = "Action was successful.";
                success = true;
            }
            else
            {
                opsStatus = "Action could not be executed. Please try again or contact your Sys Admin.";
            }
            return Json(new { status = opsStatus, success = success });
        }
       
        public ActionResult RepollDealer(int accountId)
        {
            var affecteRow = _dataAccess.RepollDealer(accountId);
            bool success = false;
            string opsStatus = string.Empty;
            if (affecteRow > 0)
            {
                opsStatus = "Action was successful.";
                success = true;
            }
            else
            {
                opsStatus = "Action could not be executed. Please try again or contact your Sys Admin.";
            }
            return Json(new { status = opsStatus, success = success });
        }
    }
}

AAA_CSR_Support_Tool/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AAA CSR Support Tool</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/DataTables/datatables.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/jquery.validate.min.js")
    @Scripts.Render("~/Scripts/jquery.validate.unobtrusive.min.js")
    @Scripts.Render("~/DataTables/datatables.min.js")
    @Scripts.Render("~/DataTables/dataTables.fixedHeader.min.js")
    @RenderSection("scripts", required: false)

    <style>
        .dropdown-menu{
            background-color:#686363;
            color:white;
        }

        .field-validation-error{color:red;}

        .dropdown-menu > ul > li > a{
            color:white !important;
        }
    </style>
</head>
<body>
    <div  id="my_menu" class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("AAA CSR Support Tool", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li id="homenet-menu" class="dropdown">
                        <a href="#" id = "netmenu">AAA</a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Homenet Dealers", "Index", "Homenet")</li>
                            <li>@Html.ActionLink("Add Dealer Code", "AddDealer", "Homenet")</li>
                            <li>@Html.ActionLink("Change Dealer Name", "Index", "Dealer")</li>
                        </ul>
                    </li>
                    <li></li>
                </ul>
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div style="height:750px;">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>Gaolline Solutions &copy; @DateTime.Now.Year - AAA CSR Support Tool</p>
        </footer>
    </div>
  
</body>
</html>
<script>
    $(document).ready(function () {
        $("#netmenu").attr("class", "dropdown-toggle");
        $("#netmenu").attr("data-toggle", "dropdown");
        $("#netmenu").attr("aria-haspopup", "true");
        $("#netmenu").attr("aria-expanded", "false");
        $("#netmenu").attr("role", "menu");

        $("#homenet-menu").mouseenter(function () {
            $("#homenet-menu").attr("class", "dropdown open");
        });
        $("#homenet-menu").mouseleave(function () {
            $("#homenet-menu").attr("class", "dropdown");
        });
    });
</script>